version: "2"

services:
  ixia-c-ixhw-server:
    image: ghcr.io/open-traffic-generator/ixia-c-ixhw-server:0.11.1-1
    restart: always
    ports:
      - "5000:5000"
      - "5001:5001"
    command:
      - "dotnet"
      - "otg-ixhw.dll"
      - "--trace"
      - "--log-level"
      - "trace"
      - "--grpc-trace-collector"
      - "jaeger:4317"
  ixia-c-gnmi-server:
    image: ghcr.io/open-traffic-generator/ixia-c-gnmi-server:1.11.1
    profiles: ["all", "gnmi"]
    restart: always
    ports:
      - "50051:50051"
    depends_on:
      ixia-c-controller:
        condition: service_started
    command:
      - "-http-server"
      - "https://ixia-c-controller:8443"
      - "--debug"
  ixia-c-controller:
    image: ghcr.io/open-traffic-generator/ixia-c-controller:0.0.1-3865
    restart: always
    ports:
      - "8443:8443"
      - "40051:40051"
    depends_on:
      ixia-c-ixhw-server:
        condition: service_started
    command:
      - "--accept-eula"
      - "--debug"
      - "--ixia-c-ixhw-server"
      - "ixia-c-ixhw-server:5001"
  jaeger:
    image: jaegertracing/all-in-one:latest
    profiles: ["all", "otlp"]
    restart: always
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
      - "16685:16685"

